"use client";

import { useState } from "react";
import { integrationDefinitions, type IntegrationStatus } from "@/lib/integrations";

const statusCopy: Record<IntegrationStatus, string> = { connected: "Connected", not_connected: "Not connected", not_enabled: "Not enabled" };

export default function IntegrationsPanel() {
  const [showPolicy, setShowPolicy] = useState(false);

  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#5269d8]">T21 · SCOPED INTEGRATIONS</p><h2 id="integrations-heading" className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-[#192235]">Connect only what the workflow needs</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#68748a]">External services are isolated behind explicit boundaries. This first integration layer shows what is active and keeps optional connections read-only until deliberately enabled.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#dfe4ff] bg-[#f6f7ff] px-3 py-2 text-xs font-semibold text-[#5269d8]"><span className="h-2 w-2 rounded-full bg-[#5269d8]" />Scoped</span></div>
    <div className="mt-6 grid gap-3 md:grid-cols-2">{integrationDefinitions.map((integration) => { const connected = integration.status === "connected"; const pending = integration.status === "not_connected"; return <article key={integration.name} className="rounded-xl border border-[#e3e7ee] bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-semibold text-[#192235]">{integration.name}</h3><p className="mt-2 text-xs leading-5 text-[#68748a]">{integration.purpose}</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] ${connected ? "bg-[#e4f3e8] text-[#4d8c65]" : pending ? "bg-[#eef1ff] text-[#5269d8]" : "bg-[#f3f5f8] text-[#8d98a9]"}`}>{statusCopy[integration.status]}</span></div><p className="mt-4 text-[11px] font-semibold uppercase tracking-[0.1em] text-[#8d98a9]">Access: {integration.access.replace("_", " ")}</p></article>; })}</div>
    <div className="mt-4 rounded-xl border border-[#e3e7ee] bg-[#fafbfc] p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#8d98a9]">Integration policy</p><p className="mt-2 text-sm font-semibold text-[#192235]">Review before any external data leaves the workspace.</p></div><button type="button" onClick={() => setShowPolicy((current) => !current)} className="rounded-lg border border-[#d8dee8] bg-white px-3 py-2 text-xs font-semibold text-[#526075] hover:border-[#bfc8d6]">{showPolicy ? "Hide policy" : "Show policy"}</button></div>{showPolicy && <ul className="mt-4 grid gap-2 text-xs leading-5 text-[#68748a] sm:grid-cols-2"><li className="rounded-lg bg-white p-3">Start read-only and workspace-scoped.</li><li className="rounded-lg bg-white p-3">Keep provider credentials server-side.</li><li className="rounded-lg bg-white p-3">Show the exact data and destination before sharing.</li><li className="rounded-lg bg-white p-3">Do not send messages or create tasks automatically.</li></ul>}<p className="mt-4 text-xs leading-5 text-[#8d98a9]">No external account was connected and no workspace data was transmitted by this panel.</p></div>
  </div>;
}
