const controls = [
  { label: "Credentials", detail: "Provider keys stay server-side and are not exposed through browser variables.", status: "Protected" },
  { label: "Workspace access", detail: "Supabase authentication and workspace-scoped row-level policies protect durable records.", status: "Protected" },
  { label: "Uploaded files", detail: "Documents use private, workspace-scoped storage and member-aware access rules.", status: "Protected" },
  { label: "AI responses", detail: "Responses API calls use store:false; prompts and model output are not logged by the app.", status: "Protected" },
];

export default function PrivacyPanel() {
  return <div>
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#4d8c65]">T20 · PRIVACY & CONTROL</p><h2 id="privacy-heading" className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-[#192235]">Make data controls visible</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#68748a]">Review the protections currently applied to this workspace. Deletion stays deliberate and scoped; this screen never removes data automatically.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-[#cfe5d6] bg-[#f5fbf6] px-3 py-2 text-xs font-semibold text-[#4d8c65]"><span className="h-2 w-2 rounded-full bg-[#53b67b]" />Controls active</span></div>
    <div className="mt-6 grid gap-3 md:grid-cols-2">{controls.map((control) => <article key={control.label} className="rounded-xl border border-[#e3e7ee] bg-white p-4"><div className="flex items-start justify-between gap-3"><h3 className="text-sm font-semibold text-[#192235]">{control.label}</h3><span className="rounded-full bg-[#e4f3e8] px-2.5 py-1 text-[10px] font-bold uppercase tracking-[0.1em] text-[#4d8c65]">{control.status}</span></div><p className="mt-2 text-xs leading-5 text-[#68748a]">{control.detail}</p></article>)}</div>
    <div className="mt-4 rounded-xl border border-[#e3e7ee] bg-[#fafbfc] p-4 sm:p-5"><p className="text-xs font-bold uppercase tracking-[0.14em] text-[#8d98a9]">Workspace data controls</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><a href="#context" className="rounded-lg border border-[#d8dee8] bg-white p-3 text-sm font-semibold text-[#526075] hover:border-[#bfc8d6]">Review or delete context<span className="mt-1 block text-xs font-normal text-[#8d98a9]">Manual records</span></a><a href="#documents" className="rounded-lg border border-[#d8dee8] bg-white p-3 text-sm font-semibold text-[#526075] hover:border-[#bfc8d6]">Review or delete files<span className="mt-1 block text-xs font-normal text-[#8d98a9]">Private documents</span></a><a href="#evidence" className="rounded-lg border border-[#d8dee8] bg-white p-3 text-sm font-semibold text-[#526075] hover:border-[#bfc8d6]">Review or delete evidence<span className="mt-1 block text-xs font-normal text-[#8d98a9]">Source-backed items</span></a></div><p className="mt-4 text-xs leading-5 text-[#8d98a9]">Retention automation and full workspace deletion are intentionally not enabled yet. No records are deleted from this panel.</p></div>
  </div>;
}
