"use client";

import AuthPanel from "./auth-panel";
import UiIcon from "./ui-icons";
import Link from "next/link";

export default function PublicLandingPage() {
  return <main className="public-landing">
    <header className="public-landing-header"><Link className="public-landing-brand" href="/"><span className="kit-brand-mark"><UiIcon name="sparkle" size={18} /></span><span><strong>Bootstrap PM</strong><small>From questions to impact</small></span></Link><div className="public-landing-header-action"><AuthPanel triggerLabel="Use Bootstrap PM" /></div></header>
    <section className="public-landing-hero" aria-labelledby="public-landing-title"><div className="public-landing-kicker">PRODUCT MANAGEMENT WORKSPACE</div><h1 id="public-landing-title">Turn product questions into evidence-backed decisions.</h1><p>Bootstrap PM helps Product Managers move from an unclear question to evidence, decisions, and useful product outputs while keeping the reasoning behind the work connected.</p><div className="public-landing-actions"><AuthPanel triggerLabel="Use Bootstrap PM" /><a className="public-landing-secondary" href="#how-it-works">See how it works <UiIcon name="chevron-down" size={14} /></a></div><div className="public-landing-proof"><span>Question</span><UiIcon name="chevron-right" size={14} /><span>Context</span><UiIcon name="chevron-right" size={14} /><span>Evidence</span><UiIcon name="chevron-right" size={14} /><span>Decision</span><UiIcon name="chevron-right" size={14} /><span>Artifact</span></div></section>
    <section className="public-landing-section public-landing-value" aria-labelledby="value-title"><div className="public-landing-section-intro"><p className="pm-eyebrow">WHY BOOTSTRAP PM</p><h2 id="value-title">Built for real product work.</h2></div><ul><li><UiIcon name="compass" size={17} /><span>Ask the right product question.</span></li><li><UiIcon name="scan" size={17} /><span>Ground decisions in evidence.</span></li><li><UiIcon name="check" size={17} /><span>Challenge assumptions before they become roadmap commitments.</span></li><li><UiIcon name="file" size={17} /><span>Create usable PRDs, decision records, and experiment plans.</span></li><li><UiIcon name="layers" size={17} /><span>Keep the reasoning behind the decision connected to the work.</span></li></ul></section>
    <section id="how-it-works" className="public-landing-section public-landing-how" aria-labelledby="how-title"><div className="public-landing-section-intro"><p className="pm-eyebrow">HOW IT WORKS</p><h2 id="how-title">A connected path from question to impact.</h2></div><ol><li><span>01</span><strong>Ask</strong><p>Start with the product question you need to answer.</p></li><li><span>02</span><strong>Understand</strong><p>Bring together context, evidence, and research.</p></li><li><span>03</span><strong>Decide</strong><p>Validate assumptions, compare options, and make the call.</p></li><li><span>04</span><strong>Deliver</strong><p>Turn the decision into a useful product output.</p></li></ol></section>
    <section className="public-landing-section public-landing-audience" aria-labelledby="audience-title"><div><p className="pm-eyebrow">FOR PRODUCT MANAGERS</p><h2 id="audience-title">For the work between a customer problem and a confident decision.</h2></div><p>Customer problems · New opportunities · Feature decisions · Onboarding issues · Pricing questions · Market research · Product strategy · Experiments</p></section>
    <section className="public-landing-cta" aria-labelledby="cta-title"><p className="pm-eyebrow">READY TO WORK</p><h2 id="cta-title">Ready to work through a product decision?</h2><AuthPanel triggerLabel="Use Bootstrap PM" /></section>
    <footer className="public-landing-footer"><span>Bootstrap PM</span><span>Question → Context → Evidence → Decision → Artifact</span></footer>
  </main>;
}
